services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/agrix
    depends_on:
      - mysql

  mysql:
    container_name: agrix-db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix
