services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mysql:database

  mysql:
    container_name: agrix-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix